axes:
	gcc axes.c -o axes
read_accel:
	gcc read_accel.c -o read_accel
calib_accel:
	gcc calib_accel.c -o calib_accel
shock_detect:
	gcc shock_detect.c -o shock_detect
shock_buffer:
	gcc shock_buffer.c -o shock_buffer